version: '3'

networks:
  microservices-network:
    driver: bridge
  db-network:
    driver: bridge
  client-network:
    driver: bridge
  kibana-network:
    driver: bridge

services:

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - client-network
  #   depends_on:
  #     - nginx

  nginx:
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - microservices-network
      - client-network
    depends_on:
      - authentication-microservice
  authentication-microservice:
    build:
      context: ./backend/authentication-microservice
      dockerfile: Dockerfile
    depends_on:
      - tokens-microservice
      - master-server
      - slave-server
    networks:
      - microservices-network
      - db-network

  tokens-microservice:
    build:
      context: ./backend/tokens-microservice
      dockerfile: Dockerfile
    networks:
      - microservices-network

  postgres:
    build:
      context: ./backend/DB/postgres
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

  master-server:
    build:
      context: ./backend/DB/master-server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - db-network

  slave-server:
    build:
      context: ./backend/DB/slave-server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - db-network
  elasticsearch:
    build:
      context: ./backend/logs/elasticsearch
      dockerfile: Dockerfile
    networks:
      - kibana-network
  kibana:
    build:
      context: ./backend/logs/kibana
      dockerfile: Dockerfile
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - kibana-network

volumes:
  postgres-data:
